-- MySQL Script generated by MySQL Workbench
-- Sun Aug 12 20:10:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema course_selection
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `course_selection` ;

-- -----------------------------------------------------
-- Schema course_selection
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `course_selection` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
SHOW WARNINGS;
USE `course_selection` ;

-- -----------------------------------------------------
-- Table `College`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `College` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `College` (
  `col_code` INT NOT NULL,
  `col_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`col_code`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `col_code_UNIQUE` ON `College` (`col_code` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Department` (
  `dep_code` INT NOT NULL,
  `col_code` INT NOT NULL,
  `dep_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dep_code`, `col_code`),
  CONSTRAINT `fk_Department_College1`
    FOREIGN KEY (`col_code`)
    REFERENCES `College` (`col_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Department_College1_idx` ON `Department` (`col_code` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Student` (
  `stu_id` INT NOT NULL,
  `stu_name` VARCHAR(45) NOT NULL,
  `stu_grade` TINYINT(3) NOT NULL,
  `stu_gender` TINYINT(1) NULL,
  `dep_code` INT NULL,
  PRIMARY KEY (`stu_id`),
  CONSTRAINT `fk_Student_Department`
    FOREIGN KEY (`dep_code`)
    REFERENCES `Department` (`dep_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Student_Department_idx` ON `Student` (`dep_code` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `stu_id_UNIQUE` ON `Student` (`stu_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Instructor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Instructor` (
  `ins_id` INT NOT NULL,
  `ins_name` VARCHAR(45) NOT NULL,
  `dep_code` INT NOT NULL,
  PRIMARY KEY (`ins_id`),
  CONSTRAINT `fk_Instructor_Department1`
    FOREIGN KEY (`dep_code`)
    REFERENCES `Department` (`dep_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Instructor_Department1_idx` ON `Instructor` (`dep_code` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ins_id_UNIQUE` ON `Instructor` (`ins_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Course` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Course` (
  `crs_id` INT NOT NULL,
  `crs_title` VARCHAR(45) NOT NULL,
  `crs_credits` INT NOT NULL,
  `crs_elective` TINYINT(1) NULL,
  `crs_time` VARCHAR(45) NULL,
  `crs_location` VARCHAR(45) NULL,
  `crs_limits` INT NULL,
  `crs_codecard_required` TINYINT(1) NULL,
  `ins_id` INT NOT NULL,
  PRIMARY KEY (`crs_id`),
  CONSTRAINT `fk_Course_Instructor1`
    FOREIGN KEY (`ins_id`)
    REFERENCES `Instructor` (`ins_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Course_Instructor1_idx` ON `Course` (`ins_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `crs_id_UNIQUE` ON `Course` (`crs_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Student_select_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student_select_Course` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Student_select_Course` (
  `Student_stu_id` INT NOT NULL,
  `Course_crs_id` INT NOT NULL,
  `stu_crs_number_assigned` INT NULL,
  `stu_crs_number_selected` INT NULL,
  PRIMARY KEY (`Student_stu_id`, `Course_crs_id`),
  CONSTRAINT `fk_Student_has_Course_Student1`
    FOREIGN KEY (`Student_stu_id`)
    REFERENCES `Student` (`stu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Course_Course1`
    FOREIGN KEY (`Course_crs_id`)
    REFERENCES `Course` (`crs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Student_has_Course_Course1_idx` ON `Student_select_Course` (`Course_crs_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Student_has_Course_Student1_idx` ON `Student_select_Course` (`Student_stu_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
